### ISSUE TITLE
ponyfill

### ISSUE THREAD

**Issue by ChrisKretschmer** [sindresorhus/number-is-nan#6]
Your code seems to be the negative example of the ponyfill page:

https://github.com/sindresorhus/ponyfill

Is that by purpose or am i missing something?

**Comment by SamVerschueren** [comment]
It's not the negative example, but you are right that it does not entirely comply with what is described.

The reason it's not the negative example is because this module is not overriding `Number.isNaN` globally like it's done in the [polyfill](https://github.com/sindresorhus/ponyfill#polyfill) section.

The reason it does not entirely comply is because it does not match this statement

> Ponyfills should never use the native API, even if available

It was pointed out and discussed [right here](https://github.com/sindresorhus/ponyfill/issues/2).

**Comment by sindresorhus** [comment]
Yes, I think I did this module before defining `ponyfill` and then later just called it a `ponyfill`. In this case, it doesn't matter, as the native implementation is exactly the same as this ponyfill.
